spring:
  data:
    mongodb:
      # uri는 보안을 위해 환경변수(MONGO_URI)로 주입받습니다.
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8089

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLXNlY3JldC1rZXktd2l0aC1sb25nLWxlbmd0aA==
  expiration: 86400000 # 24시간 (밀리초 단위)