spring.application.name=example1
server.port=8080

# ===============================
# 1. H2 Database ??
# ===============================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# 2. JPA ??
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# 3. JWT ?? (??? ?)
# ===============================
# HS256 ????? ?? 32???(?? 32?) ??? ? ???? ?????.
jwt.secret=v3ry-s3cr3t-k3y-f0r-jwt-sign1ng-must-b3-l0ng3r-th4n-th1s
# Long expireTimeMs = 1000 * 60 * 60L;
jwt.expiration=3600000

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
