spring.application.name=example1
server.port=8081

# ===============================
# 1. H2 ?????? ?? ??
# ===============================
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# 2. H2 ?? ??? (?????? DB ???)
# ===============================
# ?? ??: http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# 3. JPA ? Hibernate ??
# ===============================
# ?? ?? (H2? ????? MySQL ??? ???? ?????? H2Dialect ??)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ?? ?? ? ??? ?? ?? (none, validate, update, create, create-drop)
spring.jpa.hibernate.ddl-auto=update

# ???? SQL ??? ??? ??
spring.jpa.show-sql=true

# SQL ??? ??? ?? ????? ??
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# 4. Mustache ??? ??
# ===============================
# ??? HttpServletRequest? ??(Attribute)? ?? ???? ??
spring.mustache.servlet.expose-request-attributes=true

# ?? ?? ??
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
